service: serverless-template

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1
  profile: serverless-template
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:Scan
          Resource: "*"

functions:
  scan:
    handler: src/handler.scan
    events:
      - http:
          path: /scan/{id}
          method: get
          cors: true
      - http:
          path: /scan/
          method: get
          cors: true

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: serverless-example-template
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
